FROM python:3.10-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
RUN apt-get update
RUN apt-get -y install postgresql-client-14 tesseract-ocr
WORKDIR /app
RUN mkdir "media"
RUN mkdir "media/temp"
RUN mkdir "backup"
RUN mkdir "staticfiles"
COPY . /app/

RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput
EXPOSE 8000
# RQ worker
CMD ["python", "manage.py", "rqworker", "ocr"]