FROM python:3.10-bookworm
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
RUN apt-get update
RUN apt-get -y install postgresql-client-14 ffmpeg cmake
WORKDIR /app
RUN git clone https://github.com/ggerganov/whisper.cpp.git
WORKDIR /app/whisper.cpp
RUN /app/whisper.cpp/models/download-ggml-model.sh base.en
RUN /app/whisper.cpp/models/download-ggml-model.sh base
RUN /app/whisper.cpp/models/download-ggml-model.sh small.en
RUN /app/whisper.cpp/models/download-ggml-model.sh small
RUN /app/whisper.cpp/models/download-ggml-model.sh medium.en
RUN /app/whisper.cpp/models/download-ggml-model.sh medium
RUN cmake -B build
RUN cmake --build build --config Release -j 8
WORKDIR /app
#RUN curl https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_amd64.tar.gz -L -o piper_amd64.tar.gz
#RUN tar -xvf piper_amd64.tar.gz
#RUN rm piper_amd64.tar.gz
#RUN chmod +x piper
#WORKDIR /app/piper
#RUN curl https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/high/en_GB-cori-high.onnx?download=true -L -o en_GB-cori-high.onnx
#RUN curl https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/high/en_GB-cori-high.onnx.json?download=true.json -L -o en_GB-cori-high.onnx.json
RUN mkdir "/app/media"
RUN mkdir "/app/media/temp"
RUN mkdir "/app/backup"
RUN mkdir "/app/staticfiles"
COPY . /app/

RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput
EXPOSE 8000
# RQ worker
CMD ["python", "manage.py", "rqworker", "transcribe"]