FROM noatgnu/cupcake-base:0.1.0
#WORKDIR /app
#RUN git clone https://github.com/ggerganov/whisper.cpp.git
#WORKDIR /app/whisper.cpp
#RUN /app/whisper.cpp/models/download-ggml-model.sh base.en
#RUN /app/whisper.cpp/models/download-ggml-model.sh base
#RUN /app/whisper.cpp/models/download-ggml-model.sh small.en
#RUN /app/whisper.cpp/models/download-ggml-model.sh small
#RUN /app/whisper.cpp/models/download-ggml-model.sh medium.en
#RUN /app/whisper.cpp/models/download-ggml-model.sh medium
#RUN make
#WORKDIR /app
#RUN curl https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_amd64.tar.gz -L -o piper_amd64.tar.gz
#RUN tar -xvf piper_amd64.tar.gz
#RUN rm piper_amd64.tar.gz
#RUN chmod +x piper
#WORKDIR /app/piper
#RUN curl https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/high/en_GB-cori-high.onnx?download=true -L -o en_GB-cori-high.onnx
#RUN curl https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/cori/high/en_GB-cori-high.onnx.json?download=true.json -L -o en_GB-cori-high.onnx.json
#RUN mkdir "/app/media"
#RUN mkdir "/app/media/temp"
#RUN mkdir "/app/backup"
#RUN mkdir "/app/staticfiles"
#COPY . /app/

#RUN pip install -r requirements.txt
#RUN python manage.py collectstatic --noinput
EXPOSE 8000
# RQ worker
CMD ["python", "manage.py", "rqworker", "import-data"]