# Generated by Django 5.0.3 on 2024-03-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolsIOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.BigIntegerField()),
                ('protocol_created_on', models.DateTimeField()),
                ('protocol_doi', models.TextField(blank=True, null=True)),
                ('protocol_title', models.TextField()),
                ('protocol_url', models.TextField()),
                ('protocol_version_uri', models.TextField()),
                ('protocol_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['protocol_id'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolsIOStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.BigIntegerField(db_index=True, unique=True)),
                ('step_description', models.TextField()),
                ('step_section', models.TextField(blank=True, null=True)),
                ('step_duration', models.IntegerField(blank=True, null=True)),
                ('step_section_duration', models.IntegerField(blank=True, null=True)),
                ('previous_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_step', to='cc.protocolsiostep')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cc.protocolsiomodel')),
            ],
            options={
                'ordering': ['step_id'],
            },
        ),
    ]
