# Generated by Django 5.0.3 on 2024-03-21 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_session_stepannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepannotation',
            name='annotation_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='annotations/'),
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
