# Generated by Django 5.0.3 on 2024-03-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_stepannotation_annotation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_description', models.TextField()),
                ('variation_duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='cc.protocolsiostep')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
