# Generated by Django 5.0.3 on 2024-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_stepannotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='unique_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
