# Generated by Django 5.0.3 on 2024-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_alter_session_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
