# Generated by Django 5.0.3 on 2024-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_session_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolsiostep',
            name='step_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
