# Generated by Django 5.0.3 on 2024-03-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_alter_protocolsiostep_step_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolsiostep',
            options={'ordering': ['id']},
        ),
    ]
