# Generated by Django 5.0.3 on 2024-03-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_alter_protocolsiostep_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProtocolsIOModel',
            new_name='ProtocolModel',
        ),
        migrations.RenameModel(
            old_name='ProtocolsIOStep',
            new_name='ProtocolStep',
        ),
    ]
