# Generated by Django 5.0.3 on 2024-03-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0010_rename_protocolsiomodel_protocolmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolstep',
            name='original',
            field=models.BooleanField(default=True),
        ),
    ]
