# Generated by Django 5.0.3 on 2024-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0015_session_created_at_session_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
