# Generated by Django 5.0.3 on 2024-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0016_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeeper',
            name='current_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timekeeper',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
