# Generated by Django 5.0.3 on 2024-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0020_protocolmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmodel',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
