# Generated by Django 5.0.3 on 2024-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0021_protocolmodel_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolmodel',
            name='protocol_created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='protocol_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='protocol_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='protocol_version_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
