# Generated by Django 5.0.3 on 2024-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0023_protocolmodel_editors_protocolmodel_viewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepannotation',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
