# Generated by Django 5.0.3 on 2024-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0024_stepannotation_transcribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepannotation',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
