# Generated by Django 5.0.3 on 2024-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0025_stepannotation_language_stepannotation_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepannotation',
            name='annotation_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch'), ('other', 'Other'), ('checklist', 'Checklist'), ('counter', 'Counter')], default='text', max_length=10),
        ),
    ]
