# Generated by Django 5.0.3 on 2024-04-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0026_alter_stepannotation_annotation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCUserChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_user_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_unique_id', models.TextField(blank=True, null=True)),
                ('session_token', models.TextField(blank=True, null=True)),
                ('session_key', models.TextField(blank=True, null=True)),
                ('session_secret', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_session', to='cc.session')),
                ('users', models.ManyToManyField(blank=True, related_name='webrtc_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_channels', models.ManyToManyField(blank=True, related_name='webrtc_sessions', to='cc.webrtcuserchannel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCUserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp', models.JSONField()),
                ('from_id', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_user_offers', to='cc.webrtcsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_user_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
