# Generated by Django 5.0.3 on 2024-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0028_alter_stepannotation_annotation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrtcuseroffer',
            name='id_type',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('host', 'Host')], default='viewer', max_length=10),
        ),
    ]
