# Generated by Django 5.0.3 on 2024-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0029_webrtcuseroffer_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrtcuserchannel',
            name='channel_type',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('host', 'Host')], default='viewer', max_length=10),
        ),
    ]
