# Generated by Django 5.0.3 on 2024-04-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0031_protocolrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolrating',
            name='complexity_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='protocolrating',
            name='duration_rating',
            field=models.IntegerField(default=0),
        ),
    ]
