# Generated by Django 5.0.3 on 2024-04-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0032_alter_protocolrating_complexity_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
