# Generated by Django 5.0.4 on 2024-04-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0035_alter_stepannotation_annotation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmodel',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolsection',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolstep',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepvariation',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timekeeper',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
