# Generated by Django 5.0.4 on 2024-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0036_protocolmodel_remote_id_protocolsection_remote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepannotation',
            name='annotation_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch'), ('other', 'Other'), ('checklist', 'Checklist'), ('counter', 'Counter'), ('table', 'Table'), ('alignment', 'Alignment'), ('calculator', 'Calculator'), ('molarity-calculator', 'Molarity Calculator')], default='text', max_length=20),
        ),
    ]
