# Generated by Django 5.0.4 on 2024-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0038_alter_stepannotation_annotation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmodel',
            name='model_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
