# Generated by Django 5.0.4 on 2024-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0039_protocolmodel_model_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepannotation',
            name='scratched',
            field=models.BooleanField(default=False),
        ),
    ]
