# Generated by Django 5.0.4 on 2024-05-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0043_tag_alter_protocoltag_tag_alter_steptag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepannotation',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cc.protocolstep'),
        ),
    ]
