# Generated by Django 5.0.4 on 2024-05-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0044_alter_stepannotation_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', to='cc.annotationfolder')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_folders', to='cc.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stepannotation',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cc.annotationfolder'),
        ),
    ]
