# Generated by Django 5.0.4 on 2024-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0045_annotationfolder_stepannotation_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepannotation',
            name='annotation_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
