# Generated by Django 5.0.4 on 2024-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0048_remove_annotationfolder_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepannotation',
            name='annotation_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch'), ('other', 'Other'), ('checklist', 'Checklist'), ('counter', 'Counter'), ('table', 'Table'), ('alignment', 'Alignment'), ('calculator', 'Calculator'), ('mcalculator', 'Molarity Calculator'), ('randomization', 'Randomization')], default='text', max_length=20),
        ),
    ]
