# Generated by Django 5.0.4 on 2024-05-08 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0049_alter_stepannotation_annotation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepAnnotation',
            new_name='Annotation',
        ),
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Reagent',
        ),
    ]
