# Generated by Django 5.0.4 on 2024-05-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0050_rename_stepannotation_annotation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProtocolIngredient',
            new_name='ProtocolReagent',
        ),
        migrations.RenameModel(
            old_name='StepIngredient',
            new_name='StepReagent',
        ),
    ]
