# Generated by Django 5.0.4 on 2024-05-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0051_rename_protocolingredient_protocolreagent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolreagent',
            old_name='ingredient',
            new_name='reagent',
        ),
        migrations.RenameField(
            model_name='stepreagent',
            old_name='ingredient',
            new_name='reagent',
        ),
    ]
