# Generated by Django 5.0.4 on 2024-05-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0052_rename_ingredient_protocolreagent_reagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolreagent',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='cc.protocolmodel'),
        ),
        migrations.AlterField(
            model_name='stepreagent',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='cc.protocolstep'),
        ),
    ]
