# Generated by Django 5.0.4 on 2024-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0053_alter_protocolreagent_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepreagent',
            name='scalable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stepreagent',
            name='scalable_factor',
            field=models.FloatField(default=1.0),
        ),
    ]
