# Generated by Django 5.0.4 on 2024-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0054_stepreagent_scalable_stepreagent_scalable_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
