# Generated by Django 5.0.4 on 2024-05-19 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0057_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolstep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
