# Generated by Django 5.0.4 on 2024-05-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0058_protocolstep_created_at_protocolstep_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.TextField()),
                ('instrument_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('remote_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('host_port', models.IntegerField()),
                ('host_protocol', models.CharField(max_length=255)),
                ('host_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='annotationfolder',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolrating',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolreagent',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocoltag',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepreagent',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steptag',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch'), ('other', 'Other'), ('checklist', 'Checklist'), ('counter', 'Counter'), ('table', 'Table'), ('alignment', 'Alignment'), ('calculator', 'Calculator'), ('mcalculator', 'Molarity Calculator'), ('randomization', 'Randomization'), ('instrument', 'Instrument')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='InstrumentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.BigIntegerField(blank=True, null=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_usage', to='cc.annotation')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_usage', to='cc.instrument')),
                ('remote_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_usages', to='cc.remotehost')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='annotationfolder',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_folders', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='project',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='protocolmodel',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='protocolrating',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_ratings', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='protocolsection',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_sections', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='protocolstep',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_steps', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='session',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='stepvariation',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_variations', to='cc.remotehost'),
        ),
        migrations.AddField(
            model_name='timekeeper',
            name='remote_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_keeper', to='cc.remotehost'),
        ),
    ]
