# Generated by Django 5.0.4 on 2024-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0059_instrument_remotehost_annotationfolder_remote_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remotehost',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='remotehost',
            name='host_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
