# Generated by Django 5.0.6 on 2024-05-31 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0062_instrumentusage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentusage',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_usage', to='cc.annotation'),
        ),
    ]
