# Generated by Django 5.0.6 on 2024-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0063_alter_instrumentusage_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentusage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
