# Generated by Django 5.0.6 on 2024-06-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0064_instrumentusage_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('shelf', 'Shelf'), ('box', 'Box'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('room', 'Room'), ('other', 'Other')], default='shelf', max_length=20)),
                ('object_name', models.TextField()),
                ('object_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.BigIntegerField(blank=True, null=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('remote_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_objects', to='cc.remotehost')),
                ('stored_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_objects', to='cc.storageobject')),
            ],
        ),
        migrations.CreateModel(
            name='StoredReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.BigIntegerField(blank=True, null=True)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_reagents', to='cc.reagent')),
                ('remote_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_reagents', to='cc.remotehost')),
                ('storage_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_reagents', to='cc.storageobject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_reagents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
