# Generated by Django 5.0.6 on 2024-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0065_storageobject_storedreagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
