# Generated by Django 5.0.6 on 2024-06-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0066_storedreagent_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageobject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='storedreagent',
            options={'ordering': ['id']},
        ),
    ]
