# Generated by Django 5.0.6 on 2024-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0067_alter_storageobject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageobject',
            name='png_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='png_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
