# Generated by Django 5.0.6 on 2024-06-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0068_storageobject_png_base64_storedreagent_png_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
