# Generated by Django 5.0.6 on 2024-06-08 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0069_storedreagent_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storageobject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storageobject',
            name='object_type',
            field=models.CharField(choices=[('shelf', 'Shelf'), ('box', 'Box'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('room', 'Room'), ('building', 'Building'), ('floor', 'Floor'), ('other', 'Other')], default='shelf', max_length=20),
        ),
    ]
