# Generated by Django 5.0.6 on 2024-06-09 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0071_storedreagent_shareable_reagentaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentaction',
            name='step_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_actions', to='cc.stepreagent'),
        ),
        migrations.AlterField(
            model_name='reagentaction',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reagentaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
