# Generated by Django 5.0.6 on 2024-06-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0072_reagentaction_step_reagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
