# Generated by Django 5.1.3 on 2024-11-28 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0074_labgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='access_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='access_lab_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_reagents', to='cc.labgroup'),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='access_users',
            field=models.ManyToManyField(blank=True, related_name='shared_reagents', to=settings.AUTH_USER_MODEL),
        ),
    ]
