# Generated by Django 5.1.3 on 2024-11-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0075_storedreagent_access_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanDisease',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('accession', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cross_references', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='MSUniqueVocabularies',
            fields=[
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('term_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('taxon', models.IntegerField()),
                ('official_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['official_name'],
            },
        ),
        migrations.CreateModel(
            name='SubcellularLocation',
            fields=[
                ('location_identifier', models.TextField(blank=True, null=True)),
                ('topology_identifier', models.TextField(blank=True, null=True)),
                ('orientation_identifier', models.TextField(blank=True, null=True)),
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_a', models.TextField(blank=True, null=True)),
                ('part_of', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('gene_ontology', models.TextField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cross_references', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='MetadataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('column_position', models.IntegerField(blank=True, default=0, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('not_applicable', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_reagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_columns', to='cc.storedreagent')),
            ],
            options={
                'ordering': ['column_position'],
            },
        ),
    ]
