# Generated by Django 5.1.3 on 2024-11-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0076_humandisease_msuniquevocabularies_species_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labgroup',
            old_name='group_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='labgroup',
            old_name='group_name',
            new_name='name',
        ),
    ]
