# Generated by Django 5.1.3 on 2024-11-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0077_rename_group_description_labgroup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='created_by_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reagents', to='cc.project'),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
