# Generated by Django 5.1.3 on 2024-11-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0078_storedreagent_created_by_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='created_by_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reagents', to='cc.protocolmodel'),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='created_by_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reagents', to='cc.session'),
        ),
    ]
