# Generated by Django 5.1.3 on 2024-12-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0079_storedreagent_created_by_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='metadata_columns',
            field=models.ManyToManyField(blank=True, related_name='annotations', to='cc.metadatacolumn'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch'), ('other', 'Other'), ('checklist', 'Checklist'), ('counter', 'Counter'), ('table', 'Table'), ('alignment', 'Alignment'), ('calculator', 'Calculator'), ('mcalculator', 'Molarity Calculator'), ('randomization', 'Randomization'), ('instrument', 'Instrument'), ('metadata', 'Metadata')], default='text', max_length=20),
        ),
    ]
