# Generated by Django 5.1.3 on 2024-12-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0080_annotation_metadata_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unimod',
            fields=[
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
    ]
