# Generated by Django 5.1.3 on 2024-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0081_unimod'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='metadata_columns',
            field=models.ManyToManyField(blank=True, related_name='instruments', to='cc.metadatacolumn'),
        ),
    ]
