# Generated by Django 5.1.3 on 2024-12-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0082_instrument_metadata_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='metadata_columns',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='metadata_columns',
        ),
    ]
