# Generated by Django 5.1.3 on 2024-12-07 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0083_remove_annotation_metadata_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacolumn',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_columns', to='cc.annotation'),
        ),
        migrations.AddField(
            model_name='metadatacolumn',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_columns', to='cc.instrument'),
        ),
    ]
