# Generated by Django 5.1.3 on 2024-12-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0084_metadatacolumn_annotation_metadatacolumn_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_actions', to='cc.session'),
        ),
    ]
