# Generated by Django 5.1.4 on 2025-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0087_instrumentjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
