# Generated by Django 5.1.4 on 2025-02-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0089_instrumentjob_staff_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentjob',
            name='sample_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='sample_type',
            field=models.CharField(choices=[('wcl', 'Whole Cell Lysate'), ('ip', 'Immunoprecipitate'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cc.session'),
        ),
    ]
