# Generated by Django 5.1.4 on 2025-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0090_instrumentjob_sample_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
