# Generated by Django 5.1.4 on 2025-02-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0092_instrumentjob_amount_instrumentjob_cost_center_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentjob',
            old_name='unit',
            new_name='injection_unit',
        ),
        migrations.RenameField(
            model_name='instrumentjob',
            old_name='amount',
            new_name='injection_volume',
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='search_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='search_engine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='search_engine_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='stored_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_jobs', to='cc.storedreagent'),
        ),
    ]
