# Generated by Django 5.1.4 on 2025-02-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0094_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
