# Generated by Django 5.1.4 on 2025-02-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0095_delete_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgroup',
            name='default_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_groups', to='cc.storageobject'),
        ),
    ]
