# Generated by Django 5.1.4 on 2025-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0096_labgroup_default_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageobject',
            name='access_lab_groups',
            field=models.ManyToManyField(blank=True, related_name='storage_objects', to='cc.labgroup'),
        ),
    ]
