# Generated by Django 5.1.6 on 2025-03-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0102_alter_metadatacolumn_options_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='stored_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cc.storedreagent'),
        ),
    ]
