# Generated by Django 5.1.6 on 2025-03-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0103_annotation_stored_reagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentjob',
            name='injection_volume',
            field=models.FloatField(blank=True, default='uL', null=True),
        ),
    ]
