# Generated by Django 5.1.6 on 2025-03-12 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0104_alter_instrumentjob_injection_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacolumn',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadatacolumn',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadatacolumn',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MetadataTableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('columns', models.ManyToManyField(blank=True, related_name='metadata_table_templates', to='cc.metadatacolumn')),
                ('lab_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_group_metadata_table_templates', to='cc.labgroup')),
                ('service_lab_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lab_group_metadata_table_templates', to='cc.labgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_table_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
