# Generated by Django 5.1.6 on 2025-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0105_metadatacolumn_auto_generated_metadatacolumn_hidden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatatabletemplate',
            old_name='columns',
            new_name='user_columns',
        ),
        migrations.AddField(
            model_name='metadatatabletemplate',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadatatabletemplate',
            name='staff_columns',
            field=models.ManyToManyField(blank=True, related_name='assigned_metadata_table_templates', to='cc.metadatacolumn'),
        ),
    ]
