# Generated by Django 5.1.6 on 2025-03-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0106_rename_columns_metadatatabletemplate_user_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentjob',
            name='selected_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_jobs', to='cc.metadatatabletemplate'),
        ),
    ]
