# Generated by Django 5.1.6 on 2025-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0107_instrumentjob_selected_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentjob',
            name='injection_unit',
            field=models.TextField(blank=True, default='uL', null=True),
        ),
        migrations.AlterField(
            model_name='instrumentjob',
            name='injection_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
