# Generated by Django 5.1.6 on 2025-03-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0108_alter_instrumentjob_injection_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentjob',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentjob',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
