# Generated by Django 5.1.6 on 2025-03-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0109_instrumentjob_completion_date_instrumentjob_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentjob',
            old_name='completion_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='instrumentjob',
            old_name='submission_date',
            new_name='submitted_at',
        ),
    ]
