# Generated by Django 5.1.6 on 2025-03-14 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0110_rename_completion_date_instrumentjob_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacolumn',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_columns', to='cc.protocolmodel'),
        ),
    ]
