# Generated by Django 5.1.6 on 2025-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0111_metadatacolumn_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritemetadataoption',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
