# Generated by Django 5.1.7 on 2025-03-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0113_instrument_max_days_ahead_pre_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentusage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_instrument_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
