# Generated by Django 5.1.7 on 2025-03-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0114_alter_instrumentusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationfolder',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_folders', to='cc.instrument'),
        ),
        migrations.AddField(
            model_name='annotationfolder',
            name='stored_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_folders', to='cc.storedreagent'),
        ),
        migrations.AlterField(
            model_name='annotationfolder',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_folders', to='cc.session'),
        ),
    ]
