# Generated by Django 5.1.7 on 2025-03-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0115_annotationfolder_instrument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['id']},
        ),
    ]
