# Generated by Django 5.1.7 on 2025-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0116_alter_instrument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
