# Generated by Django 5.1.7 on 2025-04-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0117_instrument_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatatabletemplate',
            name='field_mask_mapping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
