# Generated by Django 5.2 on 2025-05-05 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0119_externalcontactdetails_externalcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportinformation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_location', to='cc.storageobject'),
        ),
        migrations.AddField(
            model_name='supportinformation',
            name='maintenance_frequency_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportinformation',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportinformation',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportinformation',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
