# Generated by Django 5.2 on 2025-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0120_supportinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
