# Generated by Django 5.2 on 2025-05-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0121_maintenancelog_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='annotation_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='cc.annotationfolder'),
        ),
    ]
