# Generated by Django 5.2 on 2025-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0124_messagethread_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='low_stock_threshold',
            field=models.FloatField(blank=True, help_text='Threshold quantity for low stock notifications', null=True),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='notify_on_low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
