# Generated by Django 5.2 on 2025-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0125_storedreagent_last_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreagent',
            name='last_expiry_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='notify_days_before_expiry',
            field=models.IntegerField(blank=True, default=14, help_text='Days before expiration to send notification', null=True),
        ),
        migrations.AddField(
            model_name='storedreagent',
            name='notify_on_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
