# Generated by Django 5.2 on 2025-05-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0126_storedreagent_last_expiry_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_low_stock', models.BooleanField(default=True)),
                ('notify_on_expiry', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stored_reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='cc.storedreagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stored_reagent')},
            },
        ),
    ]
