# Generated by Django 5.2 on 2025-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0127_reagentsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='last_maintenance_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_warranty_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
