# Generated by Django 5.2.1 on 2025-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0128_instrument_last_maintenance_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='days_before_maintenance_notification',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='days_before_warranty_notification',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
