# Generated by Django 5.2.1 on 2025-06-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0129_instrument_days_before_maintenance_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeper',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_keeper', to='cc.session'),
        ),
    ]
