# Generated by Django 5.2.3 on 2025-06-25 12:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0131_historicalannotation_historicalannotationfolder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSiteSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('site_name', models.CharField(default='CUPCAKE', help_text='Name displayed in the application', max_length=255)),
                ('site_tagline', models.CharField(blank=True, help_text='Tagline or description', max_length=500, null=True)),
                ('logo', models.TextField(blank=True, help_text='Site logo', max_length=100, null=True)),
                ('favicon', models.TextField(blank=True, help_text='Site favicon', max_length=100, null=True)),
                ('banner_enabled', models.BooleanField(default=False, help_text='Enable site-wide banner')),
                ('banner_text', models.TextField(blank=True, help_text='Banner message text', null=True)),
                ('banner_color', models.CharField(default='#0066cc', help_text='Banner background color (hex)', max_length=7)),
                ('banner_text_color', models.CharField(default='#ffffff', help_text='Banner text color (hex)', max_length=7)),
                ('banner_dismissible', models.BooleanField(default=True, help_text='Allow users to dismiss banner')),
                ('primary_color', models.CharField(default='#0066cc', help_text='Primary theme color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary theme color (hex)', max_length=7)),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Site Settings',
                'verbose_name_plural': 'historical Site Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('site_name', models.CharField(default='CUPCAKE', help_text='Name displayed in the application', max_length=255)),
                ('site_tagline', models.CharField(blank=True, help_text='Tagline or description', max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Site logo', null=True, upload_to='site_settings/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='site_settings/favicons/')),
                ('banner_enabled', models.BooleanField(default=False, help_text='Enable site-wide banner')),
                ('banner_text', models.TextField(blank=True, help_text='Banner message text', null=True)),
                ('banner_color', models.CharField(default='#0066cc', help_text='Banner background color (hex)', max_length=7)),
                ('banner_text_color', models.CharField(default='#ffffff', help_text='Banner text color (hex)', max_length=7)),
                ('banner_dismissible', models.BooleanField(default=True, help_text='Allow users to dismiss banner')),
                ('primary_color', models.CharField(default='#0066cc', help_text='Primary theme color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary theme color (hex)', max_length=7)),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
