# Generated by Django 5.2.3 on 2025-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0132_historicalsitesettings_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
