# Generated by Django 5.2.3 on 2025-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0133_alter_historicalsitesettings_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaintenancelog',
            name='maintenance_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='maintenance_date',
            field=models.DateTimeField(),
        ),
    ]
