# Generated by Django 5.2.3 on 2025-06-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0136_backuplog_historicalbackuplog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationfolder',
            name='is_shared_document_folder',
            field=models.BooleanField(default=False, help_text='Indicates if this folder is specifically for shared documents (file annotations)'),
        ),
        migrations.AddField(
            model_name='historicalannotationfolder',
            name='is_shared_document_folder',
            field=models.BooleanField(default=False, help_text='Indicates if this folder is specifically for shared documents (file annotations)'),
        ),
    ]
