# Generated by Django 5.2.3 on 2025-06-28 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0137_annotationfolder_is_shared_document_folder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationfolder',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this folder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_annotation_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotationfolder',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who owns this folder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
