# Generated by Django 5.2.3 on 2025-06-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0138_annotationfolder_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('annotation', 'lab_group'), ('annotation', 'user')},
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='cc.annotationfolder'),
        ),
        migrations.AddField(
            model_name='historicaldocumentpermission',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cc.annotationfolder'),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='cc.annotation'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('annotation', 'lab_group'), ('annotation', 'user'), ('folder', 'lab_group'), ('folder', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['folder', 'user'], name='cc_document_folder__1b771e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['folder', 'lab_group'], name='cc_document_folder__f74710_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annotation__isnull', False), ('folder__isnull', True)), models.Q(('annotation__isnull', True), ('folder__isnull', False)), _connector='OR'), name='document_permission_either_annotation_or_folder'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lab_group__isnull', True), ('user__isnull', False)), models.Q(('lab_group__isnull', False), ('user__isnull', True)), _connector='OR'), name='document_permission_either_user_or_lab_group'),
        ),
    ]
