# Generated by Django 5.2.3 on 2025-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0139_alter_documentpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_annotations',
            field=models.BooleanField(default=True, help_text='Allow users to import annotation data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_instruments',
            field=models.BooleanField(default=True, help_text='Allow users to import instrument data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_lab_groups',
            field=models.BooleanField(default=True, help_text='Allow users to import lab group data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_messaging',
            field=models.BooleanField(default=False, help_text='Allow users to import messaging data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_projects',
            field=models.BooleanField(default=True, help_text='Allow users to import project data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_protocols',
            field=models.BooleanField(default=True, help_text='Allow users to import protocol data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_reagents',
            field=models.BooleanField(default=True, help_text='Allow users to import reagent and storage data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_sessions',
            field=models.BooleanField(default=True, help_text='Allow users to import session data'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_import_support_models',
            field=models.BooleanField(default=True, help_text='Allow users to import metadata and support models'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='import_archive_size_limit_mb',
            field=models.PositiveIntegerField(default=500, help_text='Maximum size of import archive in MB (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='staff_only_import_override',
            field=models.BooleanField(default=False, help_text='Only staff users can override import restrictions'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_annotations',
            field=models.BooleanField(default=True, help_text='Allow users to import annotation data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_instruments',
            field=models.BooleanField(default=True, help_text='Allow users to import instrument data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_lab_groups',
            field=models.BooleanField(default=True, help_text='Allow users to import lab group data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_messaging',
            field=models.BooleanField(default=False, help_text='Allow users to import messaging data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_projects',
            field=models.BooleanField(default=True, help_text='Allow users to import project data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_protocols',
            field=models.BooleanField(default=True, help_text='Allow users to import protocol data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_reagents',
            field=models.BooleanField(default=True, help_text='Allow users to import reagent and storage data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_sessions',
            field=models.BooleanField(default=True, help_text='Allow users to import session data'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_import_support_models',
            field=models.BooleanField(default=True, help_text='Allow users to import metadata and support models'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='import_archive_size_limit_mb',
            field=models.PositiveIntegerField(default=500, help_text='Maximum size of import archive in MB (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_only_import_override',
            field=models.BooleanField(default=False, help_text='Only staff users can override import restrictions'),
        ),
    ]
