# Generated by Django 5.2.3 on 2025-07-03 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0140_historicalsitesettings_allow_import_annotations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.UUIDField(db_index=True, unique=True)),
                ('import_started_at', models.DateTimeField(auto_now_add=True)),
                ('import_completed_at', models.DateTimeField(blank=True, null=True)),
                ('import_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='in_progress', max_length=50)),
                ('archive_path', models.TextField()),
                ('archive_size_mb', models.FloatField(blank=True, null=True)),
                ('import_options', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('total_objects_created', models.IntegerField(default=0)),
                ('total_files_imported', models.IntegerField(default=0)),
                ('total_relationships_created', models.IntegerField(default=0)),
                ('can_revert', models.BooleanField(default=True)),
                ('revert_reason', models.TextField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_imports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-import_started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_model', models.CharField(max_length=100)),
                ('from_object_id', models.IntegerField()),
                ('to_model', models.CharField(max_length=100)),
                ('to_object_id', models.IntegerField()),
                ('relationship_field', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_relationships', to='cc.importtracker')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('original_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_files', to='cc.importtracker')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('object_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_objects', to='cc.importtracker')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('import_tracker', 'model_name', 'object_id')},
            },
        ),
    ]
