# Generated by Django 5.2.4 on 2025-07-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0143_protocolstepsuggestioncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_ai_sdrf_suggestions',
            field=models.BooleanField(default=False, help_text='Enable AI-based SDRF suggestions'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_billing_module',
            field=models.BooleanField(default=True, help_text='Enable billing module for instrument usage'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_documents_module',
            field=models.BooleanField(default=True, help_text='Enable document management module'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_instruments_module',
            field=models.BooleanField(default=True, help_text='Enable instruments management module'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_lab_notebook_module',
            field=models.BooleanField(default=True, help_text='Enable lab notebook module'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_storage_module',
            field=models.BooleanField(default=True, help_text='Enable storage management module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ai_sdrf_suggestions',
            field=models.BooleanField(default=False, help_text='Enable AI-based SDRF suggestions'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_billing_module',
            field=models.BooleanField(default=True, help_text='Enable billing module for instrument usage'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_documents_module',
            field=models.BooleanField(default=True, help_text='Enable document management module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_instruments_module',
            field=models.BooleanField(default=True, help_text='Enable instruments management module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_lab_notebook_module',
            field=models.BooleanField(default=True, help_text='Enable lab notebook module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_storage_module',
            field=models.BooleanField(default=True, help_text='Enable storage management module'),
        ),
    ]
