# Generated by Django 5.2.4 on 2025-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0144_historicalsitesettings_enable_ai_sdrf_suggestions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuplog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='backuplog',
            name='cc_backuplo_started_d199e8_idx',
        ),
        migrations.RenameField(
            model_name='backuplog',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='historicalbackuplog',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['created_at'], name='cc_backuplo_created_4798d0_idx'),
        ),
    ]
