# Generated by Django 5.2.4 on 2025-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0145_alter_backuplog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='backup_frequency_days',
            field=models.PositiveIntegerField(default=7, help_text='Frequency of automatic backups in days'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='enable_backup_module',
            field=models.BooleanField(default=True, help_text='Enable backup management module'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_frequency_days',
            field=models.PositiveIntegerField(default=7, help_text='Frequency of automatic backups in days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_backup_module',
            field=models.BooleanField(default=True, help_text='Enable backup management module'),
        ),
    ]
