# Generated by Django 5.2.4 on 2025-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0147_samplepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepool',
            name='staff_metadata',
            field=models.ManyToManyField(blank=True, related_name='assigned_sample_pools', to='cc.metadatacolumn'),
        ),
        migrations.AddField(
            model_name='samplepool',
            name='template_sample',
            field=models.IntegerField(blank=True, help_text='Sample index to copy metadata from when creating this pool', null=True),
        ),
        migrations.AddField(
            model_name='samplepool',
            name='user_metadata',
            field=models.ManyToManyField(blank=True, related_name='sample_pools', to='cc.metadatacolumn'),
        ),
    ]
