# Generated by Django 5.2.4 on 2025-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0148_samplepool_staff_metadata_samplepool_template_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepool',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Whether this pool is a reference pool for channel normalization (appears in SDRF export with SN= format)'),
        ),
    ]
