# Generated by Django 5.2.4 on 2025-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0150_historicalinstrument_is_vaulted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_vaulted_object_deletion',
            field=models.BooleanField(default=False, help_text='Allow direct deletion of vaulted objects without unvaulting'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_vaulted_object_updates',
            field=models.BooleanField(default=False, help_text='Allow direct updates to vaulted objects without unvaulting'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_vaulted_session_deletion',
            field=models.BooleanField(default=False, help_text='Allow deletion of sessions connected to vaulted protocols'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='allow_vaulted_session_updates',
            field=models.BooleanField(default=False, help_text='Allow updates to sessions connected to vaulted protocols'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='staff_override_vault_protection',
            field=models.BooleanField(default=True, help_text='Allow staff users to bypass vault protection'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_vaulted_object_deletion',
            field=models.BooleanField(default=False, help_text='Allow direct deletion of vaulted objects without unvaulting'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_vaulted_object_updates',
            field=models.BooleanField(default=False, help_text='Allow direct updates to vaulted objects without unvaulting'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_vaulted_session_deletion',
            field=models.BooleanField(default=False, help_text='Allow deletion of sessions connected to vaulted protocols'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_vaulted_session_updates',
            field=models.BooleanField(default=False, help_text='Allow updates to sessions connected to vaulted protocols'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_override_vault_protection',
            field=models.BooleanField(default=True, help_text='Allow staff users to bypass vault protection'),
        ),
    ]
