---
- name: Setup and deploy application
  hosts: all
  become: true
  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Create a Python virtual environment
      command: python3 -m venv /opt/venv
      args:
        creates: /opt/venv

    - name: Install Python dependencies from requirements.txt
      pip:
        requirements: requirements.txt
        virtualenv: /opt/venv

    - name: Collect static files
      command: /opt/venv/bin/python manage.py collectstatic --noinput

    - name: Build Docker Compose services
      command: docker-compose build

    - name: Deploy Docker Compose services
      command: docker-compose up -d